### ISSUE TITLE
So trying to get broadcast-chan picked up as a dependency and it's not happening

### ISSUE THREAD

**Issue by SolarAquarion** [merijn/broadcast-chan#10]
I have broadcaast-chan installed, but yet it's not "sending" it
Setup: Encountered missing dependencies:
broadcast-chan >=0.2.0.2

**Comment by merijn** [comment]
That seems like a problem with your build tool (cabal/stack) and/or environment.

**Comment by merijn** [comment]
If I understood correctly on IRC this was a package manager issue, so closing.
