### ISSUE TITLE
New hackage release for GHC 8.10?

### ISSUE THREAD

**Issue by LeifW** [merijn/broadcast-chan#11]
I see back on March 6th the upper bound of base was bumped.
On hackage it's still saying it requires base <4.14, though - so I can't build it on GHC 8.10
Could we get a new release published to hackage?

**Comment by merijn** [comment]
Yeah, I was working on both base and unliftio-core when I noticed a potential race that I wanted to fix before making a new release. But if I don't get around to that this week I'll make sure to at least bump the base bounds.

**Comment by merijn** [comment]
Done
