### ISSUE TITLE
`Direction`s in Haddocks aren't rendered correctly

### ISSUE THREAD

**Issue by evanrelf** [merijn/broadcast-chan#13]
e.g. `['BroadcastChan' 'In':]:` gets rendered as `BroadcastChan Direction:`

https://hackage.haskell.org/package/broadcast-chan-0.2.1.1/docs/BroadcastChan.html#v:newBChanListener

Source:

<img width="691" alt="Screen Shot 2020-11-28 at 2 30 56 PM" src="https://user-images.githubusercontent.com/887196/100527328-697b5080-3186-11eb-8fd6-90cf55d97379.png">

Rendered:

<img width="703" alt="Screen Shot 2020-11-28 at 2 30 44 PM" src="https://user-images.githubusercontent.com/887196/100527330-6d0ed780-3186-11eb-80fa-f2ed4a6e2a78.png">

**Comment by merijn** [comment]
Ugh...that's unfortunate. I'll look into whether there's a way to get Haddock to render it properly.

**Comment by merijn** [comment]
Should be fixed in the newly updated docs (assuming I didn't miss any uses.

**Comment by evanrelf** [comment]
Looks good to me! Thanks.
