### ISSUE TITLE
`BroadcastChan.Throw.{read,Write}BChan` in `MonadIO m => m`?

### ISSUE THREAD

**Issue by evanrelf** [merijn/broadcast-chan#14]
Is there any technical reason why the `readBChan` and `writeBChan` functions from the `BroadcastChan.Throw` module are in `IO` and not some `MonadIO m => m`? Since the equivalent functions from the `BroadcastChan` module are in `MonadIO m => m`.

**Comment by merijn** [comment]
Yeah, that technical reason is: I seem to have completely missed/forgotten them when I changed that ;)

I'll fix it when I work on the next release Real Soon Now (TM)

**Comment by evanrelf** [comment]
Cool 🙂
