### ISSUE TITLE
Optionally always keep the most recent value

### ISSUE THREAD

**Issue by colonelpanic8** [merijn/broadcast-chan#16]
For my use case, it would be quite useful if the broadcast channel would always retain the most recent value that was written to it (even in the case where there are 0 readers).

I realize that it may not make sense to implement this in this library, but I thought I might mention it just in case it does.

**Comment by merijn** [comment]
It doesn't really make much sense in the way this library works. I think it'd be fairly trivial to implement on top of this when I fix #12, though. Simply make a new data structure that has both a `BChan` and a single `MVar`/`TVar`, then have every write go to both the channel and to the `MVar`. Then use non-blocking read to check the channel and (if it's empty) read the last value from the MVar and return that instead. Or something along those lines.
