### ISSUE TITLE
New hackage release supporting base-4.15 & base-4.16

### ISSUE THREAD

**Issue by jchia** [merijn/broadcast-chan#17]

**Comment by merijn** [comment]
The main reason I haven't made a new release yet is that there's a nasty race condition I hadn't considered originally. I have, an extremely hacky, fix for that in https://github.com/merijn/broadcast-chan/tree/test I was working on a better API capable of reporting multiple exceptions, but I got stuck on making that work and got distracted by work.

I can make a release of the current hacky fix, but then a proper fix ends up immediately breaking the API on a new release... :\

**Comment by jchia** [comment]
I think a base version bump together with the hacky fix that doesn't break the API is a good start. I wasn't aware of the race condition; I was just trying to get taffybar to build with GHC  9.0 and GHC 9.2.

**Comment by merijn** [comment]
I made a new candidate release: https://hackage.haskell.org/package/broadcast-chan-0.2.1.2/candidate if it works for you I'll make a new release Soon (TM)

**Comment by jchia** [comment]
Thanks. I was able to run 'stack benchmark' and didn't encounter any problem. I left it running for several hours before killing it. I also used the candidate to build and run taffybar and I think it works for me.

**Comment by merijn** [comment]
Now on hackage.
