### ISSUE TITLE
Request for code explanation

### ISSUE THREAD

**Issue by saurabhnanda** [merijn/broadcast-chan#2]
I'm planning to use this library but want to be really sure of what it's doing and its intended purpose. Would it be possible to explain at a conceptual level how the code is working and how it fixes the problem with using `dupChan` for creating broadcast channels? (especially for the case where we may have zero readers). What's the kind of overhead/performance-hit that one can expect from using `broadcast-chan`?

**Comment by merijn** [comment]
New hackage release should fix this.
