### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by colonelpanic8** [merijn/broadcast-chan#9]
I need to get broadcast-chan into stackage because it is a dependency of taffybar. Would you like to put it under your name or mine.

**Comment by colonelpanic8** [comment]
@merijn it seems broadcast-chan was removed from stackage here:
https://github.com/commercialhaskell/stackage/commit/117ac9f8e75d4f2c5717b480f06985940f440298

Any idea what is going on? I wouldn't mind being the stackage maintainer if that is necessary.

**Comment by colonelpanic8** [comment]
This is done now

**Comment by merijn** [comment]
I guess this should've been closed already :)
